packages:
  - docs/embroider-css-modules
  - docs/sample-v2-addon
  - packages/ember-codemod-remove-ember-css-modules
  - packages/embroider-css-modules
  - packages/type-css-modules
  - tests/embroider-css-modules
