import { assert, normalizeFile } from '@codemod-utils/tests';

import { getClassToStyles } from '../../../../src/utils/css/index.js';
import { testOnPosix } from '../../../helpers/index.js';

testOnPosix(
  'utils | css | get-class-to-styles > complex case (3)',
  function () {
    const file = normalizeFile([
      `.container {`,
      `  column-gap: 2.5rem;`,
      `  display: grid;`,
      `  grid-template-areas:`,
      `    "summary summary"`,
      `    "previous-button next-button";`,
      `  grid-template-columns: 1fr 1fr;`,
      `  grid-template-rows: 1fr auto;`,
      `  height: 100%;`,
      `  overflow: hidden;`,
      `  row-gap: 1rem;`,
      `  width: 100%;`,
      `}`,
      ``,
      `.summary {`,
      `  color: #455a64;`,
      `  display: grid;`,
      `  font-size: 0.875rem;`,
      `  grid-area: summary;`,
      `  grid-template-areas:`,
      `    "music-format"`,
      `    "annual-revenue"`,
      `    "relevant-years";`,
      `  grid-template-columns: 1fr;`,
      `  grid-template-rows: repeat(3, auto);`,
      `  overflow-y: auto;`,
      `}`,
      ``,
      `.music-format {`,
      `  color: rgb(247 252 251 / 90%);`,
      `  display: flex;`,
      `  font-size: 1rem;`,
      `  grid-area: music-format;`,
      `  margin-bottom: 0.5rem;`,
      `  word-break: break-all;`,
      `}`,
      ``,
      `.marker {`,
      `  align-items: center;`,
      `  background-color: rgb(247 252 251 / 90%);`,
      `  border-radius: 0.5rem;`,
      `  display: flex;`,
      `  height: 1em;`,
      `  justify-content: center;`,
      `  margin-right: 0.25rem;`,
      `  padding: 0.125rem;`,
      `  width: 1rem;`,
      `}`,
      ``,
      `.annual-revenue {`,
      `  font-size: 0.8rem;`,
      `  grid-area: annual-revenue;`,
      `}`,
      ``,
      `.relevant-years {`,
      `  font-size: 0.8rem;`,
      `  grid-area: relevant-years;`,
      `}`,
      ``,
      `.highlight {`,
      `  color: rgb(247 252 251 / 90%);`,
      `}`,
      ``,
      `.previous-button,`,
      `.next-button {`,
      `  align-items: center;`,
      `  display: flex;`,
      `  height: 2rem;`,
      `  justify-content: center;`,
      `  margin: 0.25rem;`,
      `}`,
      ``,
      `.previous-button {`,
      `  grid-area: previous-button;`,
      `}`,
      ``,
      `.next-button {`,
      `  grid-area: next-button;`,
      `}`,
      ``,
      `.icon {`,
      `  color: rgb(247 252 251 / 90%);`,
      `}`,
      ``,
      `.container.flat {`,
      `  column-gap: 1rem;`,
      `  grid-template-areas: "previous-button summary next-button";`,
      `  grid-template-columns: 2.5rem 1fr 2.5rem;`,
      `  grid-template-rows: minmax(3rem, 1fr);`,
      `}`,
      ``,
      `.container.flat .summary.horizontal-layout {`,
      `  gap: 0.5rem;`,
      `  grid-template-areas: "music-format annual-revenue relevant-years";`,
      `  grid-template-columns: 40% 1fr 1fr;`,
      `  grid-template-rows: 1fr;`,
      `}`,
      ``,
      `.container.flat .annual-revenue,`,
      `.container.flat .relevant-years {`,
      `  display: flex;`,
      `  flex-direction: column;`,
      `}`,
      ``,
      `.container.flat .previous-button,`,
      `.container.flat .next-button {`,
      `  background: linear-gradient(36deg, #7cb342 16%, #4b830d 84%);`,
      `  border: 0;`,
      `}`,
      ``,
      `.music-format.small-font-size {`,
      `  font-size: 0.875rem;`,
      `  margin: 0;`,
      `}`,
      ``,
    ]);

    assert.deepStrictEqual(
      getClassToStyles(file),
      new Map([
        [
          'container',
          [
            {
              classes: ['container'],
              code: normalizeFile([
                `.container {`,
                `  column-gap: 2.5rem;`,
                `  display: grid;`,
                `  grid-template-areas:`,
                `    "summary summary"`,
                `    "previous-button next-button";`,
                `  grid-template-columns: 1fr 1fr;`,
                `  grid-template-rows: 1fr auto;`,
                `  height: 100%;`,
                `  overflow: hidden;`,
                `  row-gap: 1rem;`,
                `  width: 100%;`,
                `}`,
              ]),
              location: {
                end: { column: 1, line: 13, offset: 267 },
                start: { column: 1, line: 1, offset: 0 },
              },
              selector: '.container',
            },
            {
              classes: ['container', 'flat'],
              code: normalizeFile([
                `.container.flat {`,
                `  column-gap: 1rem;`,
                `  grid-template-areas: "previous-button summary next-button";`,
                `  grid-template-columns: 2.5rem 1fr 2.5rem;`,
                `  grid-template-rows: minmax(3rem, 1fr);`,
                `}`,
              ]),
              location: {
                end: { column: 1, line: 90, offset: 1582 },
                start: { column: 1, line: 85, offset: 1396 },
              },
              selector: '.container.flat',
            },
            {
              classes: ['container', 'flat', 'summary', 'horizontal-layout'],
              code: normalizeFile([
                `.container.flat .summary.horizontal-layout {`,
                `  gap: 0.5rem;`,
                `  grid-template-areas: "music-format annual-revenue relevant-years";`,
                `  grid-template-columns: 40% 1fr 1fr;`,
                `  grid-template-rows: 1fr;`,
                `}`,
              ]),
              location: {
                end: { column: 1, line: 97, offset: 1779 },
                start: { column: 1, line: 92, offset: 1584 },
              },
              selector: '.container.flat .summary.horizontal-layout',
            },
            {
              classes: ['container', 'flat', 'annual-revenue'],
              code: normalizeFile([
                `.container.flat .annual-revenue {`,
                `  display: flex;`,
                `  flex-direction: column;`,
                `}`,
              ]),
              location: {
                end: { column: 1, line: 103, offset: 1892 },
                start: { column: 1, line: 99, offset: 1781 },
              },
              selector: '.container.flat .annual-revenue',
            },
            {
              classes: ['container', 'flat', 'relevant-years'],
              code: normalizeFile([
                `.container.flat .relevant-years {`,
                `  display: flex;`,
                `  flex-direction: column;`,
                `}`,
              ]),
              location: {
                end: { column: 1, line: 103, offset: 1892 },
                start: { column: 1, line: 99, offset: 1781 },
              },
              selector: '.container.flat .relevant-years',
            },
            {
              classes: ['container', 'flat', 'previous-button'],
              code: normalizeFile([
                `.container.flat .previous-button {`,
                `  background: linear-gradient(36deg, #7cb342 16%, #4b830d 84%);`,
                `  border: 0;`,
                `}`,
              ]),
              location: {
                end: { column: 1, line: 109, offset: 2037 },
                start: { column: 1, line: 105, offset: 1894 },
              },
              selector: '.container.flat .previous-button',
            },
            {
              classes: ['container', 'flat', 'next-button'],
              code: normalizeFile([
                `.container.flat .next-button {`,
                `  background: linear-gradient(36deg, #7cb342 16%, #4b830d 84%);`,
                `  border: 0;`,
                `}`,
              ]),
              location: {
                end: { column: 1, line: 109, offset: 2037 },
                start: { column: 1, line: 105, offset: 1894 },
              },
              selector: '.container.flat .next-button',
            },
          ],
        ],
        [
          'summary',
          [
            {
              classes: ['summary'],
              code: normalizeFile([
                `.summary {`,
                `  color: #455a64;`,
                `  display: grid;`,
                `  font-size: 0.875rem;`,
                `  grid-area: summary;`,
                `  grid-template-areas:`,
                `    "music-format"`,
                `    "annual-revenue"`,
                `    "relevant-years";`,
                `  grid-template-columns: 1fr;`,
                `  grid-template-rows: repeat(3, auto);`,
                `  overflow-y: auto;`,
                `}`,
              ]),
              location: {
                end: { column: 1, line: 27, offset: 535 },
                start: { column: 1, line: 15, offset: 269 },
              },
              selector: '.summary',
            },
          ],
        ],
        [
          'music-format',
          [
            {
              classes: ['music-format'],
              code: normalizeFile([
                `.music-format {`,
                `  color: rgb(247 252 251 / 90%);`,
                `  display: flex;`,
                `  font-size: 1rem;`,
                `  grid-area: music-format;`,
                `  margin-bottom: 0.5rem;`,
                `  word-break: break-all;`,
                `}`,
              ]),
              location: {
                end: { column: 1, line: 36, offset: 700 },
                start: { column: 1, line: 29, offset: 537 },
              },
              selector: '.music-format',
            },
            {
              classes: ['music-format', 'small-font-size'],
              code: normalizeFile([
                `.music-format.small-font-size {`,
                `  font-size: 0.875rem;`,
                `  margin: 0;`,
                `}`,
              ]),
              location: {
                end: { column: 1, line: 114, offset: 2108 },
                start: { column: 1, line: 111, offset: 2039 },
              },
              selector: '.music-format.small-font-size',
            },
          ],
        ],
        [
          'marker',
          [
            {
              classes: ['marker'],
              code: normalizeFile([
                `.marker {`,
                `  align-items: center;`,
                `  background-color: rgb(247 252 251 / 90%);`,
                `  border-radius: 0.5rem;`,
                `  display: flex;`,
                `  height: 1em;`,
                `  justify-content: center;`,
                `  margin-right: 0.25rem;`,
                `  padding: 0.125rem;`,
                `  width: 1rem;`,
                `}`,
              ]),
              location: {
                end: { column: 1, line: 48, offset: 925 },
                start: { column: 1, line: 38, offset: 702 },
              },
              selector: '.marker',
            },
          ],
        ],
        [
          'annual-revenue',
          [
            {
              classes: ['annual-revenue'],
              code: normalizeFile([
                `.annual-revenue {`,
                `  font-size: 0.8rem;`,
                `  grid-area: annual-revenue;`,
                `}`,
              ]),
              location: {
                end: { column: 1, line: 53, offset: 996 },
                start: { column: 1, line: 50, offset: 927 },
              },
              selector: '.annual-revenue',
            },
          ],
        ],
        [
          'relevant-years',
          [
            {
              classes: ['relevant-years'],
              code: normalizeFile([
                `.relevant-years {`,
                `  font-size: 0.8rem;`,
                `  grid-area: relevant-years;`,
                `}`,
              ]),
              location: {
                end: { column: 1, line: 58, offset: 1067 },
                start: { column: 1, line: 55, offset: 998 },
              },
              selector: '.relevant-years',
            },
          ],
        ],
        [
          'highlight',
          [
            {
              classes: ['highlight'],
              code: normalizeFile([
                `.highlight {`,
                `  color: rgb(247 252 251 / 90%);`,
                `}`,
              ]),
              location: {
                end: { column: 1, line: 62, offset: 1116 },
                start: { column: 1, line: 60, offset: 1069 },
              },
              selector: '.highlight',
            },
          ],
        ],
        [
          'previous-button',
          [
            {
              classes: ['previous-button'],
              code: normalizeFile([
                `.previous-button {`,
                `  align-items: center;`,
                `  display: flex;`,
                `  height: 2rem;`,
                `  justify-content: center;`,
                `  margin: 0.25rem;`,
                `}`,
              ]),
              location: {
                end: { column: 1, line: 71, offset: 1254 },
                start: { column: 1, line: 64, offset: 1118 },
              },
              selector: '.previous-button',
            },
            {
              classes: ['previous-button'],
              code: normalizeFile([
                `.previous-button {`,
                `  grid-area: previous-button;`,
                `}`,
              ]),
              location: {
                end: { column: 1, line: 75, offset: 1306 },
                start: { column: 1, line: 73, offset: 1256 },
              },
              selector: '.previous-button',
            },
          ],
        ],
        [
          'next-button',
          [
            {
              classes: ['next-button'],
              code: normalizeFile([
                `.next-button {`,
                `  align-items: center;`,
                `  display: flex;`,
                `  height: 2rem;`,
                `  justify-content: center;`,
                `  margin: 0.25rem;`,
                `}`,
              ]),
              location: {
                end: { column: 1, line: 71, offset: 1254 },
                start: { column: 1, line: 64, offset: 1118 },
              },
              selector: '.next-button',
            },
            {
              classes: ['next-button'],
              code: normalizeFile([
                `.next-button {`,
                `  grid-area: next-button;`,
                `}`,
              ]),
              location: {
                end: { column: 1, line: 79, offset: 1350 },
                start: { column: 1, line: 77, offset: 1308 },
              },
              selector: '.next-button',
            },
          ],
        ],
        [
          'icon',
          [
            {
              classes: ['icon'],
              code: normalizeFile([
                `.icon {`,
                `  color: rgb(247 252 251 / 90%);`,
                `}`,
              ]),
              location: {
                end: { column: 1, line: 83, offset: 1394 },
                start: { column: 1, line: 81, offset: 1352 },
              },
              selector: '.icon',
            },
          ],
        ],
      ]),
    );
  },
);
