import { EOL } from 'node:os';

import { assert, normalizeFile } from '@codemod-utils/tests';

import { getClassToStyles } from '../../../../src/utils/css/index.js';
import { testOnPosix } from '../../../helpers/index.js';

testOnPosix(
  'utils | css | get-class-to-styles > complex case (2)',
  function () {
    const file = normalizeFile([
      `.container {`,
      `  display: grid;`,
      `  grid-template-areas:`,
      `    "header"`,
      `    "image-container"`,
      `    "body"`,
      `    "actions";`,
      `  grid-template-columns: 1fr;`,
      `  grid-template-rows: auto auto 1fr auto;`,
      `  height: calc(100% - 2rem) !important;`,
      `  padding: 1rem;`,
      `  position: relative;`,
      `  width: calc(100% - 2rem) !important;`,
      `}`,
      ``,
      `.container:hover {`,
      `  background: #26313d;`,
      `  transform: translateY(-0.25rem);`,
      `  transition: all 0.25s;`,
      `}`,
      ``,
      `.header {`,
      `  grid-area: header;`,
      `}`,
      ``,
      `.name {`,
      `  font-size: 1.25rem;`,
      `  font-weight: 700;`,
      `  margin-bottom: 0.75rem;`,
      `}`,
      ``,
      `.image-container {`,
      `  grid-area: image-container;`,
      `  max-height: 6rem;`,
      `  max-width: 8rem;`,
      `}`,
      ``,
      `.body {`,
      `  grid-area: body;`,
      `  margin-top: 1rem;`,
      `}`,
      ``,
      `.description,`,
      `.price {`,
      `  font-size: 0.875rem;`,
      `  margin-bottom: 0.375rem;`,
      `}`,
      ``,
      `.actions {`,
      `  align-items: center;`,
      `  display: flex;`,
      `  grid-area: actions;`,
      `  justify-content: flex-end;`,
      `}`,
      ``,
      `.link {`,
      `  background: transparent;`,
      `  border: 0.0625rem solid rgb(247 252 251 / 50%);`,
      `  border-radius: 0.15rem;`,
      `  color: rgb(247 252 251 / 90%);`,
      `  font-family: Raleway, sans-serif;`,
      `  font-size: 0.875rem;`,
      `  margin-top: 0.5rem;`,
      `  padding: 0.25rem 0.5rem;`,
      `  text-decoration: none;`,
      `}`,
      ``,
      `.link::after {`,
      `  content: "";`,
      `  height: 100%;`,
      `  left: 0;`,
      `  position: absolute;`,
      `  top: 0;`,
      `  width: 100%;`,
      `}`,
      ``,
      `.link:focus {`,
      `  outline: 0;`,
      `}`,
      ``,
      `.link:focus::after {`,
      `  border: 1px solid orange;`,
      `}`,
      ``,
      `.container[data-container-query-wide] {`,
      `  column-gap: 1.5rem;`,
      `  grid-template-areas:`,
      `    "image-container header"`,
      `    "image-container body"`,
      `    "image-container actions";`,
      `  grid-template-columns: auto 1fr;`,
      `  grid-template-rows: auto 1fr auto;`,
      `}`,
      ``,
      `.container[data-container-query-wide]`,
      `  .body {`,
      `  margin-top: 0;`,
      `}`,
      ``,
      `.container[data-container-query-wide]`,
      `  .link {`,
      `  margin-top: 1rem;`,
      `}`,
      ``,
    ]);

    assert.deepStrictEqual(
      getClassToStyles(file),
      new Map([
        [
          'container',
          [
            {
              classes: ['container'],
              location: {
                end: { column: 1, line: 14, offset: 305 },
                start: { column: 1, line: 1, offset: 0 },
              },
              raw: normalizeFile([
                `.container {`,
                `  display: grid;`,
                `  grid-template-areas:`,
                `    "header"`,
                `    "image-container"`,
                `    "body"`,
                `    "actions";`,
                `  grid-template-columns: 1fr;`,
                `  grid-template-rows: auto auto 1fr auto;`,
                `  height: calc(100% - 2rem) !important;`,
                `  padding: 1rem;`,
                `  position: relative;`,
                `  width: calc(100% - 2rem) !important;`,
                `}`,
              ]),
              selector: '.container',
            },
            {
              classes: ['container'],
              location: {
                end: { column: 1, line: 20, offset: 410 },
                start: { column: 1, line: 16, offset: 307 },
              },
              raw: normalizeFile([
                `.container:hover {`,
                `  background: #26313d;`,
                `  transform: translateY(-0.25rem);`,
                `  transition: all 0.25s;`,
                `}`,
              ]),
              selector: '.container:hover',
            },
            {
              classes: ['container'],
              location: {
                end: { column: 1, line: 93, offset: 1562 },
                start: { column: 1, line: 85, offset: 1317 },
              },
              raw: normalizeFile([
                `.container[data-container-query-wide] {`,
                `  column-gap: 1.5rem;`,
                `  grid-template-areas:`,
                `    "image-container header"`,
                `    "image-container body"`,
                `    "image-container actions";`,
                `  grid-template-columns: auto 1fr;`,
                `  grid-template-rows: auto 1fr auto;`,
                `}`,
              ]),
              selector: '.container[data-container-query-wide]',
            },
            {
              classes: ['container', 'body'],
              location: {
                end: { column: 1, line: 98, offset: 1630 },
                start: { column: 1, line: 95, offset: 1564 },
              },
              raw: normalizeFile([
                `.container[data-container-query-wide]`,
                `  .body {`,
                `  margin-top: 0;`,
                `}`,
              ]),
              selector: `.container[data-container-query-wide]${EOL}  .body`,
            },
            {
              classes: ['container', 'link'],
              location: {
                end: { column: 1, line: 103, offset: 1701 },
                start: { column: 1, line: 100, offset: 1632 },
              },
              raw: normalizeFile([
                `.container[data-container-query-wide]`,
                `  .link {`,
                `  margin-top: 1rem;`,
                `}`,
              ]),
              selector: `.container[data-container-query-wide]${EOL}  .link`,
            },
          ],
        ],
        [
          'header',
          [
            {
              classes: ['header'],
              location: {
                end: { column: 1, line: 24, offset: 444 },
                start: { column: 1, line: 22, offset: 412 },
              },
              raw: normalizeFile([`.header {`, `  grid-area: header;`, `}`]),
              selector: '.header',
            },
          ],
        ],
        [
          'name',
          [
            {
              classes: ['name'],
              location: {
                end: { column: 1, line: 30, offset: 523 },
                start: { column: 1, line: 26, offset: 446 },
              },
              raw: normalizeFile([
                `.name {`,
                `  font-size: 1.25rem;`,
                `  font-weight: 700;`,
                `  margin-bottom: 0.75rem;`,
                `}`,
              ]),
              selector: '.name',
            },
          ],
        ],
        [
          'image-container',
          [
            {
              classes: ['image-container'],
              location: {
                end: { column: 1, line: 36, offset: 614 },
                start: { column: 1, line: 32, offset: 525 },
              },
              raw: normalizeFile([
                `.image-container {`,
                `  grid-area: image-container;`,
                `  max-height: 6rem;`,
                `  max-width: 8rem;`,
                `}`,
              ]),
              selector: '.image-container',
            },
          ],
        ],
        [
          'body',
          [
            {
              classes: ['body'],
              location: {
                end: { column: 1, line: 41, offset: 664 },
                start: { column: 1, line: 38, offset: 616 },
              },
              raw: normalizeFile([
                `.body {`,
                `  grid-area: body;`,
                `  margin-top: 1rem;`,
                `}`,
              ]),
              selector: '.body',
            },
          ],
        ],
        [
          'description',
          [
            {
              classes: ['description'],
              location: {
                end: { column: 1, line: 47, offset: 740 },
                start: { column: 1, line: 43, offset: 666 },
              },
              raw: normalizeFile([
                `.description {`,
                `  font-size: 0.875rem;`,
                `  margin-bottom: 0.375rem;`,
                `}`,
              ]),
              selector: '.description',
            },
          ],
        ],
        [
          'price',
          [
            {
              classes: ['price'],
              location: {
                end: { column: 1, line: 47, offset: 740 },
                start: { column: 1, line: 43, offset: 666 },
              },
              raw: normalizeFile([
                `.price {`,
                `  font-size: 0.875rem;`,
                `  margin-bottom: 0.375rem;`,
                `}`,
              ]),
              selector: '.price',
            },
          ],
        ],
        [
          'actions',
          [
            {
              classes: ['actions'],
              location: {
                end: { column: 1, line: 54, offset: 845 },
                start: { column: 1, line: 49, offset: 742 },
              },
              raw: normalizeFile([
                `.actions {`,
                `  align-items: center;`,
                `  display: flex;`,
                `  grid-area: actions;`,
                `  justify-content: flex-end;`,
                `}`,
              ]),
              selector: '.actions',
            },
          ],
        ],
        [
          'link',
          [
            {
              classes: ['link'],
              location: {
                end: { column: 1, line: 66, offset: 1125 },
                start: { column: 1, line: 56, offset: 847 },
              },
              raw: normalizeFile([
                `.link {`,
                `  background: transparent;`,
                `  border: 0.0625rem solid rgb(247 252 251 / 50%);`,
                `  border-radius: 0.15rem;`,
                `  color: rgb(247 252 251 / 90%);`,
                `  font-family: Raleway, sans-serif;`,
                `  font-size: 0.875rem;`,
                `  margin-top: 0.5rem;`,
                `  padding: 0.25rem 0.5rem;`,
                `  text-decoration: none;`,
                `}`,
              ]),
              selector: '.link',
            },
            {
              classes: ['link'],
              location: {
                end: { column: 1, line: 75, offset: 1232 },
                start: { column: 1, line: 68, offset: 1127 },
              },
              raw: normalizeFile([
                `.link::after {`,
                `  content: "";`,
                `  height: 100%;`,
                `  left: 0;`,
                `  position: absolute;`,
                `  top: 0;`,
                `  width: 100%;`,
                `}`,
              ]),
              selector: '.link::after',
            },
            {
              classes: ['link'],
              location: {
                end: { column: 1, line: 79, offset: 1263 },
                start: { column: 1, line: 77, offset: 1234 },
              },
              raw: normalizeFile([`.link:focus {`, `  outline: 0;`, `}`]),
              selector: '.link:focus',
            },
            {
              classes: ['link'],
              location: {
                end: { column: 1, line: 83, offset: 1315 },
                start: { column: 1, line: 81, offset: 1265 },
              },
              raw: normalizeFile([
                `.link:focus::after {`,
                `  border: 1px solid orange;`,
                `}`,
              ]),
              selector: '.link:focus::after',
            },
          ],
        ],
      ]),
    );
  },
);
