import { assert, normalizeFile } from '@codemod-utils/tests';

import { getClassToStyles } from '../../../../src/utils/css/index.js';
import { testOnPosix } from '../../../helpers/index.js';

testOnPosix(
  'utils | css | get-class-to-styles > complex case (1)',
  function () {
    const file = normalizeFile([
      `.container {`,
      `  align-items: start;`,
      `  display: grid;`,
      `}`,
      ``,
      `.container:not(.is-wide):not(.no-feedback) {`,
      `  column-gap: 0;`,
      `  grid-template-areas:`,
      `    "label"`,
      `    "field"`,
      `    "feedback";`,
      `  grid-template-columns: 1fr;`,
      `  grid-template-rows: auto 1fr auto;`,
      `  row-gap: 0.5rem;`,
      `}`,
      ``,
      `.container:not(.is-wide).no-feedback {`,
      `  column-gap: 0;`,
      `  grid-template-areas:`,
      `    "label"`,
      `    "field";`,
      `  grid-template-columns: 1fr;`,
      `  grid-template-rows: auto 1fr;`,
      `  row-gap: 0.5rem;`,
      `}`,
      ``,
      `.container.is-wide:not(.no-feedback) {`,
      `  column-gap: 1rem;`,
      `  grid-template-areas:`,
      `    "label field"`,
      `    "label feedback";`,
      `  grid-template-columns: 10rem 1fr;`,
      `  grid-template-rows: 1fr auto;`,
      `  row-gap: 0.5rem;`,
      `}`,
      ``,
      `.container.is-wide.no-feedback {`,
      `  column-gap: 1rem;`,
      `  grid-template-areas: "label field";`,
      `  grid-template-columns: 10rem 1fr;`,
      `  grid-template-rows: 1fr;`,
      `  row-gap: 0.5rem;`,
      `}`,
      ``,
      `.label {`,
      `  grid-area: label;`,
      `  overflow: hidden;`,
      `  word-break: break-all;`,
      `}`,
      ``,
      `.field {`,
      `  grid-area: field;`,
      `}`,
      ``,
      `.feedback {`,
      `  align-items: center;`,
      `  display: flex;`,
      `  font-size: 0.875rem;`,
      `  grid-area: feedback;`,
      `}`,
      ``,
      `.feedback.is-error {`,
      `  color: #ff5252;`,
      `}`,
      ``,
      `.message {`,
      `  margin-left: 0.5rem;`,
      `}`,
      ``,
      `/* Exceptions for mobile */`,
      `.container.is-inline:not(.is-wide):not(.no-feedback) {`,
      `  column-gap: 1rem;`,
      `  grid-template-areas:`,
      `    "field label"`,
      `    "feedback feedback";`,
      `  grid-template-columns: auto 1fr;`,
      `  grid-template-rows: 1fr auto;`,
      `  row-gap: 0.5rem;`,
      `}`,
      ``,
      `.container.is-inline:not(.is-wide).no-feedback {`,
      `  column-gap: 1rem;`,
      `  grid-template-areas: "field label";`,
      `  grid-template-columns: auto 1fr;`,
      `  grid-template-rows: 1fr;`,
      `  row-gap: 0;`,
      `}`,
      ``,
    ]);

    assert.deepStrictEqual(
      getClassToStyles(file),
      new Map([
        [
          'container',
          [
            {
              classes: ['container'],
              code: normalizeFile([
                `.container {`,
                `  align-items: start;`,
                `  display: grid;`,
                `}`,
              ]),
              line: 1,
              selector: '.container',
            },
            {
              classes: ['container', 'is-wide', 'no-feedback'],
              code: normalizeFile([
                `.container:not(.is-wide):not(.no-feedback) {`,
                `  column-gap: 0;`,
                `  grid-template-areas:`,
                `    "label"`,
                `    "field"`,
                `    "feedback";`,
                `  grid-template-columns: 1fr;`,
                `  grid-template-rows: auto 1fr auto;`,
                `  row-gap: 0.5rem;`,
                `}`,
              ]),
              line: 6,
              selector: '.container:not(.is-wide):not(.no-feedback)',
            },
            {
              classes: ['container', 'is-wide', 'no-feedback'],
              code: normalizeFile([
                `.container:not(.is-wide).no-feedback {`,
                `  column-gap: 0;`,
                `  grid-template-areas:`,
                `    "label"`,
                `    "field";`,
                `  grid-template-columns: 1fr;`,
                `  grid-template-rows: auto 1fr;`,
                `  row-gap: 0.5rem;`,
                `}`,
              ]),
              line: 17,
              selector: '.container:not(.is-wide).no-feedback',
            },
            {
              classes: ['container', 'is-wide', 'no-feedback'],
              code: normalizeFile([
                `.container.is-wide:not(.no-feedback) {`,
                `  column-gap: 1rem;`,
                `  grid-template-areas:`,
                `    "label field"`,
                `    "label feedback";`,
                `  grid-template-columns: 10rem 1fr;`,
                `  grid-template-rows: 1fr auto;`,
                `  row-gap: 0.5rem;`,
                `}`,
              ]),
              line: 27,
              selector: '.container.is-wide:not(.no-feedback)',
            },
            {
              classes: ['container', 'is-wide', 'no-feedback'],
              code: normalizeFile([
                `.container.is-wide.no-feedback {`,
                `  column-gap: 1rem;`,
                `  grid-template-areas: "label field";`,
                `  grid-template-columns: 10rem 1fr;`,
                `  grid-template-rows: 1fr;`,
                `  row-gap: 0.5rem;`,
                `}`,
              ]),
              line: 37,
              selector: '.container.is-wide.no-feedback',
            },
            {
              classes: ['container', 'is-inline', 'is-wide', 'no-feedback'],
              code: normalizeFile([
                `.container.is-inline:not(.is-wide):not(.no-feedback) {`,
                `  column-gap: 1rem;`,
                `  grid-template-areas:`,
                `    "field label"`,
                `    "feedback feedback";`,
                `  grid-template-columns: auto 1fr;`,
                `  grid-template-rows: 1fr auto;`,
                `  row-gap: 0.5rem;`,
                `}`,
              ]),
              line: 71,
              selector: '.container.is-inline:not(.is-wide):not(.no-feedback)',
            },
            {
              classes: ['container', 'is-inline', 'is-wide', 'no-feedback'],
              code: normalizeFile([
                `.container.is-inline:not(.is-wide).no-feedback {`,
                `  column-gap: 1rem;`,
                `  grid-template-areas: "field label";`,
                `  grid-template-columns: auto 1fr;`,
                `  grid-template-rows: 1fr;`,
                `  row-gap: 0;`,
                `}`,
              ]),
              line: 81,
              selector: '.container.is-inline:not(.is-wide).no-feedback',
            },
          ],
        ],
        [
          'label',
          [
            {
              classes: ['label'],
              code: normalizeFile([
                `.label {`,
                `  grid-area: label;`,
                `  overflow: hidden;`,
                `  word-break: break-all;`,
                `}`,
              ]),
              line: 45,
              selector: '.label',
            },
          ],
        ],
        [
          'field',
          [
            {
              classes: ['field'],
              code: normalizeFile([`.field {`, `  grid-area: field;`, `}`]),
              line: 51,
              selector: '.field',
            },
          ],
        ],
        [
          'feedback',
          [
            {
              classes: ['feedback'],
              code: normalizeFile([
                `.feedback {`,
                `  align-items: center;`,
                `  display: flex;`,
                `  font-size: 0.875rem;`,
                `  grid-area: feedback;`,
                `}`,
              ]),
              line: 55,
              selector: '.feedback',
            },
            {
              classes: ['feedback', 'is-error'],
              code: normalizeFile([
                `.feedback.is-error {`,
                `  color: #ff5252;`,
                `}`,
              ]),
              line: 62,
              selector: '.feedback.is-error',
            },
          ],
        ],
        [
          'message',
          [
            {
              classes: ['message'],
              code: normalizeFile([
                `.message {`,
                `  margin-left: 0.5rem;`,
                `}`,
              ]),
              line: 66,
              selector: '.message',
            },
          ],
        ],
      ]),
    );
  },
);
