import { assert, normalizeFile } from '@codemod-utils/tests';

import { getClassToStyles } from '../../../../src/utils/css/index.js';
import { testOnPosix } from '../../../helpers/index.js';

testOnPosix(
  'utils | css | get-class-to-styles > complex case (5)',
  function () {
    const file = normalizeFile([
      `.widgets {`,
      `  display: grid;`,
      `  gap: 1rem;`,
      `  grid-template-areas:`,
      `    "widget-1"`,
      `    "widget-2"`,
      `    "widget-3"`,
      `    "widget-4"`,
      `    "widget-5";`,
      `  grid-template-columns: 1fr;`,
      `  grid-template-rows: repeat(4, minmax(12rem, 75%)) 5rem;`,
      `}`,
      ``,
      `.widget-1,`,
      `.widget-2,`,
      `.widget-3,`,
      `.widget-4,`,
      `.widget-5 {`,
      `  border-radius: 0.125rem;`,
      `  overflow: hidden;`,
      `  padding: 0.75rem;`,
      `}`,
      ``,
      `.widget-1 {`,
      `  background: linear-gradient(126deg, #e91e63 16%, #ff6090 84%);`,
      `  grid-area: widget-1;`,
      `}`,
      ``,
      `.widget-2 {`,
      `  background: linear-gradient(126deg, #7cb342 16%, #aee571 84%);`,
      `  grid-area: widget-2;`,
      `}`,
      ``,
      `.widget-3 {`,
      `  background: linear-gradient(126deg, #ffa000 16%, #ffd149 84%);`,
      `  grid-area: widget-3;`,
      `}`,
      ``,
      `.widget-4 {`,
      `  background: linear-gradient(126deg, #03a9f4 16%, #67daff 84%);`,
      `  grid-area: widget-4;`,
      `}`,
      ``,
      `.widget-5 {`,
      `  background: linear-gradient(126deg, #9c27b0 16%, #d05ce3 84%);`,
      `  grid-area: widget-5;`,
      `}`,
      ``,
      `@media screen and (width <= 30rem) {`,
      `  @media (height >= 40rem) {`,
      `    .widgets {`,
      `      grid-template-rows: repeat(4, 25%) 5rem;`,
      `    }`,
      `  }`,
      `}`,
      ``,
      `@media screen and (width >= 30rem) and (width <= 60rem) {`,
      `  .widgets {`,
      `    grid-template-areas:`,
      `      "widget-1 widget-2"`,
      `      "widget-4 widget-2"`,
      `      "widget-4 widget-3"`,
      `      "widget-5 widget-3";`,
      `    grid-template-columns: 2fr 5fr;`,
      `    grid-template-rows: 3fr 1fr 2fr 1fr;`,
      `    height: 40rem;`,
      `  }`,
      ``,
      `  @media (height >= 40rem) {`,
      `    .widgets {`,
      `      grid-template-rows: 3fr 1fr 2fr 5rem;`,
      `    }`,
      `  }`,
      `}`,
      ``,
      `@media screen and (width >= 60rem) {`,
      `  .widgets {`,
      `    grid-template-areas:`,
      `      "widget-1 widget-2 widget-4"`,
      `      "widget-3 widget-3 widget-4"`,
      `      "widget-3 widget-3 widget-5";`,
      `    grid-template-columns: minmax(25%, 15rem) minmax(50%, 15rem) auto;`,
      `    grid-template-rows: 12fr 3fr 5fr;`,
      `    height: 40rem;`,
      `  }`,
      ``,
      `  @media (height >= 40rem) {`,
      `    .widgets {`,
      `      grid-template-rows: 4fr 1fr 10rem;`,
      `    }`,
      `  }`,
      `}`,
      ``,
    ]);

    assert.deepStrictEqual(
      getClassToStyles(file),
      new Map([
        [
          'widgets',
          [
            {
              classes: ['widgets'],
              code: normalizeFile([
                `.widgets {`,
                `  display: grid;`,
                `  gap: 1rem;`,
                `  grid-template-areas:`,
                `    "widget-1"`,
                `    "widget-2"`,
                `    "widget-3"`,
                `    "widget-4"`,
                `    "widget-5";`,
                `  grid-template-columns: 1fr;`,
                `  grid-template-rows: repeat(4, minmax(12rem, 75%)) 5rem;`,
                `}`,
              ]),
              line: 1,
              selector: '.widgets',
            },
            {
              classes: ['widgets'],
              code: normalizeFile([
                `.widgets {`,
                `      grid-template-rows: repeat(4, 25%) 5rem;`,
                `    }`,
              ]),
              line: 51,
              selector: '.widgets',
            },
            {
              classes: ['widgets'],
              code: normalizeFile([
                `.widgets {`,
                `    grid-template-areas:`,
                `      "widget-1 widget-2"`,
                `      "widget-4 widget-2"`,
                `      "widget-4 widget-3"`,
                `      "widget-5 widget-3";`,
                `    grid-template-columns: 2fr 5fr;`,
                `    grid-template-rows: 3fr 1fr 2fr 1fr;`,
                `    height: 40rem;`,
                `  }`,
              ]),
              line: 58,
              selector: '.widgets',
            },
            {
              classes: ['widgets'],
              code: normalizeFile([
                `.widgets {`,
                `      grid-template-rows: 3fr 1fr 2fr 5rem;`,
                `    }`,
              ]),
              line: 70,
              selector: '.widgets',
            },
            {
              classes: ['widgets'],
              code: normalizeFile([
                `.widgets {`,
                `    grid-template-areas:`,
                `      "widget-1 widget-2 widget-4"`,
                `      "widget-3 widget-3 widget-4"`,
                `      "widget-3 widget-3 widget-5";`,
                `    grid-template-columns: minmax(25%, 15rem) minmax(50%, 15rem) auto;`,
                `    grid-template-rows: 12fr 3fr 5fr;`,
                `    height: 40rem;`,
                `  }`,
              ]),
              line: 77,
              selector: '.widgets',
            },
            {
              classes: ['widgets'],
              code: normalizeFile([
                `.widgets {`,
                `      grid-template-rows: 4fr 1fr 10rem;`,
                `    }`,
              ]),
              line: 88,
              selector: '.widgets',
            },
          ],
        ],
        [
          'widget-1',
          [
            {
              classes: ['widget-1'],
              code: normalizeFile([
                `.widget-1 {`,
                `  border-radius: 0.125rem;`,
                `  overflow: hidden;`,
                `  padding: 0.75rem;`,
                `}`,
              ]),
              line: 14,
              selector: '.widget-1',
            },
            {
              classes: ['widget-1'],
              code: normalizeFile([
                `.widget-1 {`,
                `  background: linear-gradient(126deg, #e91e63 16%, #ff6090 84%);`,
                `  grid-area: widget-1;`,
                `}`,
              ]),
              line: 24,
              selector: '.widget-1',
            },
          ],
        ],
        [
          'widget-2',
          [
            {
              classes: ['widget-2'],
              code: normalizeFile([
                `.widget-2 {`,
                `  border-radius: 0.125rem;`,
                `  overflow: hidden;`,
                `  padding: 0.75rem;`,
                `}`,
              ]),
              line: 14,
              selector: '.widget-2',
            },
            {
              classes: ['widget-2'],
              code: normalizeFile([
                `.widget-2 {`,
                `  background: linear-gradient(126deg, #7cb342 16%, #aee571 84%);`,
                `  grid-area: widget-2;`,
                `}`,
              ]),
              line: 29,
              selector: '.widget-2',
            },
          ],
        ],
        [
          'widget-3',
          [
            {
              classes: ['widget-3'],
              code: normalizeFile([
                `.widget-3 {`,
                `  border-radius: 0.125rem;`,
                `  overflow: hidden;`,
                `  padding: 0.75rem;`,
                `}`,
              ]),
              line: 14,
              selector: '.widget-3',
            },
            {
              classes: ['widget-3'],
              code: normalizeFile([
                `.widget-3 {`,
                `  background: linear-gradient(126deg, #ffa000 16%, #ffd149 84%);`,
                `  grid-area: widget-3;`,
                `}`,
              ]),
              line: 34,
              selector: '.widget-3',
            },
          ],
        ],
        [
          'widget-4',
          [
            {
              classes: ['widget-4'],
              code: normalizeFile([
                `.widget-4 {`,
                `  border-radius: 0.125rem;`,
                `  overflow: hidden;`,
                `  padding: 0.75rem;`,
                `}`,
              ]),
              line: 14,
              selector: '.widget-4',
            },
            {
              classes: ['widget-4'],
              code: normalizeFile([
                `.widget-4 {`,
                `  background: linear-gradient(126deg, #03a9f4 16%, #67daff 84%);`,
                `  grid-area: widget-4;`,
                `}`,
              ]),
              line: 39,
              selector: '.widget-4',
            },
          ],
        ],
        [
          'widget-5',
          [
            {
              classes: ['widget-5'],
              code: normalizeFile([
                `.widget-5 {`,
                `  border-radius: 0.125rem;`,
                `  overflow: hidden;`,
                `  padding: 0.75rem;`,
                `}`,
              ]),
              line: 14,
              selector: '.widget-5',
            },
            {
              classes: ['widget-5'],
              code: normalizeFile([
                `.widget-5 {`,
                `  background: linear-gradient(126deg, #9c27b0 16%, #d05ce3 84%);`,
                `  grid-area: widget-5;`,
                `}`,
              ]),
              line: 44,
              selector: '.widget-5',
            },
          ],
        ],
      ]),
    );
  },
);
