import { normalizeFile } from '@codemod-utils/tests';

import { getClassNameToStyles } from '../../../../src/utils/css/index.js';

const stylesheet = normalizeFile([
  `.container {`,
  `  display: grid;`,
  `  grid-template-areas:`,
  `    "header"`,
  `    "image-container"`,
  `    "body"`,
  `    "actions";`,
  `  grid-template-columns: 1fr;`,
  `  grid-template-rows: auto auto 1fr auto;`,
  `  height: calc(100% - 2rem) !important;`,
  `  padding: 1rem;`,
  `  position: relative;`,
  `  width: calc(100% - 2rem) !important;`,
  `}`,
  ``,
  `.container:hover {`,
  `  background: #26313d;`,
  `  transform: translateY(-0.25rem);`,
  `  transition: all 0.25s;`,
  `}`,
  ``,
  `.header {`,
  `  grid-area: header;`,
  `}`,
  ``,
  `.name {`,
  `  font-size: 1.25rem;`,
  `  font-weight: 700;`,
  `  margin-bottom: 0.75rem;`,
  `}`,
  ``,
  `.image-container {`,
  `  grid-area: image-container;`,
  `  max-height: 6rem;`,
  `  max-width: 8rem;`,
  `}`,
  ``,
  `.body {`,
  `  grid-area: body;`,
  `  margin-top: 1rem;`,
  `}`,
  ``,
  `.description,`,
  `.price {`,
  `  font-size: 0.875rem;`,
  `  margin-bottom: 0.375rem;`,
  `}`,
  ``,
  `.actions {`,
  `  align-items: center;`,
  `  display: flex;`,
  `  grid-area: actions;`,
  `  justify-content: flex-end;`,
  `}`,
  ``,
  `.link {`,
  `  background: transparent;`,
  `  border: 0.0625rem solid rgb(247 252 251 / 50%);`,
  `  border-radius: 0.15rem;`,
  `  color: rgb(247 252 251 / 90%);`,
  `  font-family: Raleway, sans-serif;`,
  `  font-size: 0.875rem;`,
  `  margin-top: 0.5rem;`,
  `  padding: 0.25rem 0.5rem;`,
  `  text-decoration: none;`,
  `}`,
  ``,
  `.link::after {`,
  `  content: "";`,
  `  height: 100%;`,
  `  left: 0;`,
  `  position: absolute;`,
  `  top: 0;`,
  `  width: 100%;`,
  `}`,
  ``,
  `.link:focus {`,
  `  outline: 0;`,
  `}`,
  ``,
  `.link:focus::after {`,
  `  border: 1px solid orange;`,
  `}`,
  ``,
  `.container[data-container-query-wide] {`,
  `  column-gap: 1.5rem;`,
  `  grid-template-areas:`,
  `    "image-container header"`,
  `    "image-container body"`,
  `    "image-container actions";`,
  `  grid-template-columns: auto 1fr;`,
  `  grid-template-rows: auto 1fr auto;`,
  `}`,
  ``,
  `.container[data-container-query-wide]`,
  `  .body {`,
  `  margin-top: 0;`,
  `}`,
  ``,
  `.container[data-container-query-wide]`,
  `  .link {`,
  `  margin-top: 1rem;`,
  `}`,
  ``,
]);

export const classNameToStyles = getClassNameToStyles(stylesheet);

export const templateFile = normalizeFile([
  `<ContainerQuery`,
  `  @features={{hash wide=(width min=320)}}`,
  `  @tagName="article"`,
  `  class="container"`,
  `  data-test-product-card`,
  `>`,
  `  <header class="header">`,
  `    <h2 class="name" data-test-field="Name">`,
  `      {{@product.name}}`,
  `    </h2>`,
  `  </header>`,
  ``,
  `  <div class="image-container">`,
  `    <ProductsProductImage @src={{@product.imageUrl}} />`,
  `  </div>`,
  ``,
  `  <div class="body">`,
  `    <p`,
  `      class="description"`,
  `      data-test-field="Short Description"`,
  `    >`,
  `      {{@product.shortDescription}}`,
  `    </p>`,
  ``,
  `    <p`,
  `      class="price"`,
  `      data-test-field="Price"`,
  `    >`,
  `      {{formatPrice @product.price}}`,
  `    </p>`,
  `  </div>`,
  ``,
  `  <div class="actions">`,
  `    <LinkTo`,
  `      @model={{@product.id}}`,
  `      @route={{@redirectTo}}`,
  `      class="link"`,
  `      data-test-link="Learn More"`,
  `    >`,
  `      Learn more`,
  `    </LinkTo>`,
  `  </div>`,
  `</ContainerQuery>`,
]);
