import { normalizeFile } from '@codemod-utils/tests';

import { getClassNameToStyles } from '../../../../src/utils/css/index.js';

const stylesheet = normalizeFile([
  `.container {`,
  `  align-items: start;`,
  `  display: grid;`,
  `}`,
  ``,
  `.container:not(.is-wide):not(.no-feedback) {`,
  `  column-gap: 0;`,
  `  grid-template-areas:`,
  `    "label"`,
  `    "field"`,
  `    "feedback";`,
  `  grid-template-columns: 1fr;`,
  `  grid-template-rows: auto 1fr auto;`,
  `  row-gap: 0.5rem;`,
  `}`,
  ``,
  `.container:not(.is-wide).no-feedback {`,
  `  column-gap: 0;`,
  `  grid-template-areas:`,
  `    "label"`,
  `    "field";`,
  `  grid-template-columns: 1fr;`,
  `  grid-template-rows: auto 1fr;`,
  `  row-gap: 0.5rem;`,
  `}`,
  ``,
  `.container.is-wide:not(.no-feedback) {`,
  `  column-gap: 1rem;`,
  `  grid-template-areas:`,
  `    "label field"`,
  `    "label feedback";`,
  `  grid-template-columns: 10rem 1fr;`,
  `  grid-template-rows: 1fr auto;`,
  `  row-gap: 0.5rem;`,
  `}`,
  ``,
  `.container.is-wide.no-feedback {`,
  `  column-gap: 1rem;`,
  `  grid-template-areas: "label field";`,
  `  grid-template-columns: 10rem 1fr;`,
  `  grid-template-rows: 1fr;`,
  `  row-gap: 0.5rem;`,
  `}`,
  ``,
  `.label {`,
  `  grid-area: label;`,
  `  overflow: hidden;`,
  `  word-break: break-all;`,
  `}`,
  ``,
  `.field {`,
  `  grid-area: field;`,
  `}`,
  ``,
  `.feedback {`,
  `  align-items: center;`,
  `  display: flex;`,
  `  font-size: 0.875rem;`,
  `  grid-area: feedback;`,
  `}`,
  ``,
  `.feedback.is-error {`,
  `  color: #ff5252;`,
  `}`,
  ``,
  `.message {`,
  `  margin-left: 0.5rem;`,
  `}`,
  ``,
  `/* Exceptions for mobile */`,
  `.container.is-inline:not(.is-wide):not(.no-feedback) {`,
  `  column-gap: 1rem;`,
  `  grid-template-areas:`,
  `    "field label"`,
  `    "feedback feedback";`,
  `  grid-template-columns: auto 1fr;`,
  `  grid-template-rows: 1fr auto;`,
  `  row-gap: 0.5rem;`,
  `}`,
  ``,
  `.container.is-inline:not(.is-wide).no-feedback {`,
  `  column-gap: 1rem;`,
  `  grid-template-areas: "field label";`,
  `  grid-template-columns: auto 1fr;`,
  `  grid-template-rows: 1fr;`,
  `  row-gap: 0;`,
  `}`,
  ``,
]);

export const classNameToStyles = getClassNameToStyles(stylesheet);

export const templateFile = normalizeFile([
  `{{#let (uniqueId) as |inputId|}}`,
  `  <div`,
  `    class="container`,
  `      {{if @isInline 'is-inline'}}`,
  `      {{if @isWide 'is-wide'}}`,
  `      {{unless @errorMessage 'no-feedback'}}`,
  `      "`,
  `    data-test-field-container`,
  `  >`,
  `    <div class="label">`,
  `      {{yield (hash inputId=inputId) to="label"}}`,
  `    </div>`,
  ``,
  `    <div class="field">`,
  `      {{yield (hash inputId=inputId) to="field"}}`,
  `    </div>`,
  ``,
  `    {{#if @errorMessage}}`,
  `      <div class="feedback is-error">`,
  `        {{svgJar`,
  `          "alert"`,
  `          desc="A warning to indicate that the input field has an error"`,
  `          role="img"`,
  `        }}`,
  ``,
  `        <span class="message" data-test-error-message role="alert">`,
  `          {{@errorMessage}}`,
  `        </span>`,
  `      </div>`,
  `    {{/if}}`,
  `  </div>`,
  `{{/let}}`,
]);
