import { normalizeFile } from '@codemod-utils/tests';

import { getClassNameToStyles } from '../../../../src/utils/css/index.js';

const stylesheet = normalizeFile([
  `.checkbox {`,
  `  align-items: center;`,
  `  background-color: white;`,
  `  border: 0.125rem solid #ffd54f;`,
  `  cursor: pointer;`,
  `  display: flex;`,
  `  height: 1rem;`,
  `  justify-content: center;`,
  `  position: relative;`,
  `  width: 1rem;`,
  `}`,
  ``,
  `.checkbox:focus {`,
  `  background-color: #ffecb3;`,
  `  outline: 0;`,
  `}`,
  ``,
  `.checkbox:not(:focus) {`,
  `  border-color: transparent;`,
  `}`,
  ``,
  `.checkmark-icon {`,
  `  color: white;`,
  `}`,
  ``,
  `.is-checked {`,
  `  background-color: #1976d2;`,
  `}`,
  ``,
  `.is-disabled {`,
  `  composes: input-disabled from global;`,
  `}`,
  ``,
  `.is-disabled .checkmark-icon {`,
  `  color: #546e7a;`,
  `}`,
  ``,
]);

export const classNameToStyles = getClassNameToStyles(stylesheet);

export const templateFile = normalizeFile([
  `<UiFormField`,
  `  @errorMessage={{this.errorMessage}}`,
  `  @isInline={{@isInline}}`,
  `  @isWide={{@isWide}}`,
  `>`,
  `  <:label as |l|>`,
  `    <label data-test-label id={{concat l.inputId "-label"}}>`,
  `      {{@label}}`,
  ``,
  `      {{#if @isRequired}}`,
  `        <span aria-hidden="true">`,
  `          *`,
  `        </span>`,
  `      {{/if}}`,
  `    </label>`,
  `  </:label>`,
  ``,
  `  <:field as |f|>`,
  `    <span`,
  `      aria-checked={{if this.isChecked "true" "false"}}`,
  `      aria-disabled={{if @isDisabled "true" "false"}}`,
  `      aria-labelledby={{concat f.inputId "-label"}}`,
  `      aria-readonly={{if @isReadOnly "true" "false"}}`,
  `      aria-required={{if @isRequired "true" "false"}}`,
  `      class="checkbox`,
  `        {{if this.isChecked 'is-checked'}}`,
  `        {{if (or @isDisabled @isReadOnly) 'is-disabled'}}`,
  `        "`,
  `      data-test-field={{@label}}`,
  `      role="checkbox"`,
  `      tabindex={{unless @isDisabled "0"}}`,
  `      {{on "click" this.updateValue}}`,
  `      {{on "keypress" this.updateValueByPressingSpace}}`,
  `    >`,
  `      {{#if this.isChecked}}`,
  `        {{svgJar`,
  `          "check"`,
  `          class="checkmark-icon"`,
  `          desc="A checkmark to indicate that the input field is checked"`,
  `          role="img"`,
  `        }}`,
  `      {{/if}}`,
  `    </span>`,
  `  </:field>`,
  `</UiFormField>`,
]);
