import { EOL } from 'node:os';

import { assert, normalizeFile, test } from '@codemod-utils/tests';

import { addLocalClasses } from '../../../../src/utils/css/index.js';

test('utils | css | add-local-classes > complex case (2)', function () {
  const file = normalizeFile([
    `<ContainerQuery`,
    `  @features={{hash wide=(width min=320)}}`,
    `  @tagName="article"`,
    `  class="container"`,
    `  data-test-product-card`,
    `>`,
    `  <header class="header">`,
    `    <h2 class="name" data-test-field="Name">`,
    `      {{@product.name}}`,
    `    </h2>`,
    `  </header>`,
    ``,
    `  <div class="image-container">`,
    `    <ProductsProductImage @src={{@product.imageUrl}} />`,
    `  </div>`,
    ``,
    `  <div class="body">`,
    `    <p`,
    `      class="description"`,
    `      data-test-field="Short Description"`,
    `    >`,
    `      {{@product.shortDescription}}`,
    `    </p>`,
    ``,
    `    <p`,
    `      class="price"`,
    `      data-test-field="Price"`,
    `    >`,
    `      {{formatPrice @product.price}}`,
    `    </p>`,
    `  </div>`,
    ``,
    `  <div class="actions">`,
    `    <LinkTo`,
    `      @model={{@product.id}}`,
    `      @route={{@redirectTo}}`,
    `      class="link"`,
    `      data-test-link="Learn More"`,
    `    >`,
    `      Learn more`,
    `    </LinkTo>`,
    `  </div>`,
    `</ContainerQuery>`,
  ]);

  const classToStyles = new Map([
    [
      'container',
      [
        {
          classes: ['container'],
          code: normalizeFile([
            `.container {`,
            `  display: grid;`,
            `  grid-template-areas:`,
            `    "header"`,
            `    "image-container"`,
            `    "body"`,
            `    "actions";`,
            `  grid-template-columns: 1fr;`,
            `  grid-template-rows: auto auto 1fr auto;`,
            `  height: calc(100% - 2rem) !important;`,
            `  padding: 1rem;`,
            `  position: relative;`,
            `  width: calc(100% - 2rem) !important;`,
            `}`,
          ]),
          location: {
            end: { column: 1, line: 14, offset: 305 },
            start: { column: 1, line: 1, offset: 0 },
          },
          selector: '.container',
        },
        {
          classes: ['container'],
          code: normalizeFile([
            `.container:hover {`,
            `  background: #26313d;`,
            `  transform: translateY(-0.25rem);`,
            `  transition: all 0.25s;`,
            `}`,
          ]),
          location: {
            end: { column: 1, line: 20, offset: 410 },
            start: { column: 1, line: 16, offset: 307 },
          },
          selector: '.container:hover',
        },
        {
          classes: ['container'],
          code: normalizeFile([
            `.container[data-container-query-wide] {`,
            `  column-gap: 1.5rem;`,
            `  grid-template-areas:`,
            `    "image-container header"`,
            `    "image-container body"`,
            `    "image-container actions";`,
            `  grid-template-columns: auto 1fr;`,
            `  grid-template-rows: auto 1fr auto;`,
            `}`,
          ]),
          location: {
            end: { column: 1, line: 93, offset: 1562 },
            start: { column: 1, line: 85, offset: 1317 },
          },
          selector: '.container[data-container-query-wide]',
        },
        {
          classes: ['container', 'body'],
          code: normalizeFile([
            `.container[data-container-query-wide]`,
            `  .body {`,
            `  margin-top: 0;`,
            `}`,
          ]),
          location: {
            end: { column: 1, line: 98, offset: 1630 },
            start: { column: 1, line: 95, offset: 1564 },
          },
          selector: `.container[data-container-query-wide]${EOL}  .body`,
        },
        {
          classes: ['container', 'link'],
          code: normalizeFile([
            `.container[data-container-query-wide]`,
            `  .link {`,
            `  margin-top: 1rem;`,
            `}`,
          ]),
          location: {
            end: { column: 1, line: 103, offset: 1701 },
            start: { column: 1, line: 100, offset: 1632 },
          },
          selector: `.container[data-container-query-wide]${EOL}  .link`,
        },
      ],
    ],
    [
      'header',
      [
        {
          classes: ['header'],
          code: normalizeFile([`.header {`, `  grid-area: header;`, `}`]),
          location: {
            end: { column: 1, line: 24, offset: 444 },
            start: { column: 1, line: 22, offset: 412 },
          },
          selector: '.header',
        },
      ],
    ],
    [
      'name',
      [
        {
          classes: ['name'],
          code: normalizeFile([
            `.name {`,
            `  font-size: 1.25rem;`,
            `  font-weight: 700;`,
            `  margin-bottom: 0.75rem;`,
            `}`,
          ]),
          location: {
            end: { column: 1, line: 30, offset: 523 },
            start: { column: 1, line: 26, offset: 446 },
          },
          selector: '.name',
        },
      ],
    ],
    [
      'image-container',
      [
        {
          classes: ['image-container'],
          code: normalizeFile([
            `.image-container {`,
            `  grid-area: image-container;`,
            `  max-height: 6rem;`,
            `  max-width: 8rem;`,
            `}`,
          ]),
          location: {
            end: { column: 1, line: 36, offset: 614 },
            start: { column: 1, line: 32, offset: 525 },
          },
          selector: '.image-container',
        },
      ],
    ],
    [
      'body',
      [
        {
          classes: ['body'],
          code: normalizeFile([
            `.body {`,
            `  grid-area: body;`,
            `  margin-top: 1rem;`,
            `}`,
          ]),
          location: {
            end: { column: 1, line: 41, offset: 664 },
            start: { column: 1, line: 38, offset: 616 },
          },
          selector: '.body',
        },
      ],
    ],
    [
      'description',
      [
        {
          classes: ['description'],
          code: normalizeFile([
            `.description {`,
            `  font-size: 0.875rem;`,
            `  margin-bottom: 0.375rem;`,
            `}`,
          ]),
          location: {
            end: { column: 1, line: 47, offset: 740 },
            start: { column: 1, line: 43, offset: 666 },
          },
          selector: '.description',
        },
      ],
    ],
    [
      'price',
      [
        {
          classes: ['price'],
          code: normalizeFile([
            `.price {`,
            `  font-size: 0.875rem;`,
            `  margin-bottom: 0.375rem;`,
            `}`,
          ]),
          location: {
            end: { column: 1, line: 47, offset: 740 },
            start: { column: 1, line: 43, offset: 666 },
          },
          selector: '.price',
        },
      ],
    ],
    [
      'actions',
      [
        {
          classes: ['actions'],
          code: normalizeFile([
            `.actions {`,
            `  align-items: center;`,
            `  display: flex;`,
            `  grid-area: actions;`,
            `  justify-content: flex-end;`,
            `}`,
          ]),
          location: {
            end: { column: 1, line: 54, offset: 845 },
            start: { column: 1, line: 49, offset: 742 },
          },
          selector: '.actions',
        },
      ],
    ],
    [
      'link',
      [
        {
          classes: ['link'],
          code: normalizeFile([
            `.link {`,
            `  background: transparent;`,
            `  border: 0.0625rem solid rgb(247 252 251 / 50%);`,
            `  border-radius: 0.15rem;`,
            `  color: rgb(247 252 251 / 90%);`,
            `  font-family: Raleway, sans-serif;`,
            `  font-size: 0.875rem;`,
            `  margin-top: 0.5rem;`,
            `  padding: 0.25rem 0.5rem;`,
            `  text-decoration: none;`,
            `}`,
          ]),
          location: {
            end: { column: 1, line: 66, offset: 1125 },
            start: { column: 1, line: 56, offset: 847 },
          },
          selector: '.link',
        },
        {
          classes: ['link'],
          code: normalizeFile([
            `.link::after {`,
            `  content: "";`,
            `  height: 100%;`,
            `  left: 0;`,
            `  position: absolute;`,
            `  top: 0;`,
            `  width: 100%;`,
            `}`,
          ]),
          location: {
            end: { column: 1, line: 75, offset: 1232 },
            start: { column: 1, line: 68, offset: 1127 },
          },
          selector: '.link::after',
        },
        {
          classes: ['link'],
          code: normalizeFile([`.link:focus {`, `  outline: 0;`, `}`]),
          location: {
            end: { column: 1, line: 79, offset: 1263 },
            start: { column: 1, line: 77, offset: 1234 },
          },
          selector: '.link:focus',
        },
        {
          classes: ['link'],
          code: normalizeFile([
            `.link:focus::after {`,
            `  border: 1px solid orange;`,
            `}`,
          ]),
          location: {
            end: { column: 1, line: 83, offset: 1315 },
            start: { column: 1, line: 81, offset: 1265 },
          },
          selector: '.link:focus::after',
        },
      ],
    ],
  ]);

  assert.strictEqual(
    addLocalClasses(file, {
      classToStyles,
      isHbs: false,
    }),
    normalizeFile([
      `<ContainerQuery`,
      `  @features={{hash wide=(width min=320)}}`,
      `  @tagName="article"`,
      `  class={{styles.container}}`,
      `  data-test-product-card`,
      `>`,
      `  <header class={{styles.header}}>`,
      `    <h2 class={{styles.name}} data-test-field="Name">`,
      `      {{@product.name}}`,
      `    </h2>`,
      `  </header>`,
      ``,
      `  <div class={{styles.image-container}}>`,
      `    <ProductsProductImage @src={{@product.imageUrl}} />`,
      `  </div>`,
      ``,
      `  <div class={{styles.body}}>`,
      `    <p`,
      `      class={{styles.description}}`,
      `      data-test-field="Short Description"`,
      `    >`,
      `      {{@product.shortDescription}}`,
      `    </p>`,
      ``,
      `    <p`,
      `      class={{styles.price}}`,
      `      data-test-field="Price"`,
      `    >`,
      `      {{formatPrice @product.price}}`,
      `    </p>`,
      `  </div>`,
      ``,
      `  <div class={{styles.actions}}>`,
      `    <LinkTo`,
      `      @model={{@product.id}}`,
      `      @route={{@redirectTo}}`,
      `      class={{styles.link}}`,
      `      data-test-link="Learn More"`,
      `    >`,
      `      Learn more`,
      `    </LinkTo>`,
      `  </div>`,
      `</ContainerQuery>`,
    ]),
  );

  assert.strictEqual(
    addLocalClasses(file, {
      classToStyles,
      isHbs: true,
    }),
    normalizeFile([
      `<ContainerQuery`,
      `  @features={{hash wide=(width min=320)}}`,
      `  @tagName="article"`,
      `  class={{this.styles.container}}`,
      `  data-test-product-card`,
      `>`,
      `  <header class={{this.styles.header}}>`,
      `    <h2 class={{this.styles.name}} data-test-field="Name">`,
      `      {{@product.name}}`,
      `    </h2>`,
      `  </header>`,
      ``,
      `  <div class={{this.styles.image-container}}>`,
      `    <ProductsProductImage @src={{@product.imageUrl}} />`,
      `  </div>`,
      ``,
      `  <div class={{this.styles.body}}>`,
      `    <p`,
      `      class={{this.styles.description}}`,
      `      data-test-field="Short Description"`,
      `    >`,
      `      {{@product.shortDescription}}`,
      `    </p>`,
      ``,
      `    <p`,
      `      class={{this.styles.price}}`,
      `      data-test-field="Price"`,
      `    >`,
      `      {{formatPrice @product.price}}`,
      `    </p>`,
      `  </div>`,
      ``,
      `  <div class={{this.styles.actions}}>`,
      `    <LinkTo`,
      `      @model={{@product.id}}`,
      `      @route={{@redirectTo}}`,
      `      class={{this.styles.link}}`,
      `      data-test-link="Learn More"`,
      `    >`,
      `      Learn more`,
      `    </LinkTo>`,
      `  </div>`,
      `</ContainerQuery>`,
    ]),
  );
});
