import { assert, normalizeFile, test } from '@codemod-utils/tests';

import { addLocalClasses } from '../../../../src/utils/css/index.js';

test('utils | css | add-local-classes > simple case (4)', function () {
  const file = normalizeFile([
    `<UiFormField`,
    `  @errorMessage={{this.errorMessage}}`,
    `  @isInline={{@isInline}}`,
    `  @isWide={{@isWide}}`,
    `>`,
    `  <:label as |l|>`,
    `    <label data-test-label id={{concat l.inputId "-label"}}>`,
    `      {{@label}}`,
    ``,
    `      {{#if @isRequired}}`,
    `        <span aria-hidden="true">`,
    `          *`,
    `        </span>`,
    `      {{/if}}`,
    `    </label>`,
    `  </:label>`,
    ``,
    `  <:field as |f|>`,
    `    <span`,
    `      aria-checked={{if this.isChecked "true" "false"}}`,
    `      aria-disabled={{if @isDisabled "true" "false"}}`,
    `      aria-labelledby={{concat f.inputId "-label"}}`,
    `      aria-readonly={{if @isReadOnly "true" "false"}}`,
    `      aria-required={{if @isRequired "true" "false"}}`,
    `      class="checkbox`,
    `        {{if this.isChecked 'is-checked'}}`,
    `        {{if (or @isDisabled @isReadOnly) 'is-disabled'}}`,
    `        "`,
    `      data-test-field={{@label}}`,
    `      role="checkbox"`,
    `      tabindex={{unless @isDisabled "0"}}`,
    `      {{on "click" this.updateValue}}`,
    `      {{on "keypress" this.updateValueByPressingSpace}}`,
    `    >`,
    `      {{#if this.isChecked}}`,
    `        {{svgJar`,
    `          "check"`,
    `          class="checkmark-icon"`,
    `          desc="A checkmark to indicate that the input field is checked"`,
    `          role="img"`,
    `        }}`,
    `      {{/if}}`,
    `    </span>`,
    `  </:field>`,
    `</UiFormField>`,
  ]);

  const classToStyles = new Map([
    [
      'checkbox',
      [
        {
          classes: ['checkbox'],
          code: normalizeFile([
            `.checkbox {`,
            `  align-items: center;`,
            `  background-color: white;`,
            `  border: 0.125rem solid #ffd54f;`,
            `  cursor: pointer;`,
            `  display: flex;`,
            `  height: 1rem;`,
            `  justify-content: center;`,
            `  position: relative;`,
            `  width: 1rem;`,
            `}`,
          ]),
          location: {
            end: { column: 1, line: 11, offset: 213 },
            start: { column: 1, line: 1, offset: 0 },
          },
          selector: '.checkbox',
        },
        {
          classes: ['checkbox'],
          code: normalizeFile([
            `.checkbox:focus {`,
            `  background-color: #ffecb3;`,
            `  outline: 0;`,
            `}`,
          ]),
          location: {
            end: { column: 1, line: 16, offset: 277 },
            start: { column: 1, line: 13, offset: 215 },
          },
          selector: '.checkbox:focus',
        },
        {
          classes: ['checkbox'],
          code: normalizeFile([
            `.checkbox:not(:focus) {`,
            `  border-color: transparent;`,
            `}`,
          ]),
          location: {
            end: { column: 1, line: 20, offset: 333 },
            start: { column: 1, line: 18, offset: 279 },
          },
          selector: '.checkbox:not(:focus)',
        },
      ],
    ],
    [
      'checkmark-icon',
      [
        {
          classes: ['checkmark-icon'],
          code: normalizeFile([`.checkmark-icon {`, `  color: white;`, `}`]),
          location: {
            end: { column: 1, line: 24, offset: 370 },
            start: { column: 1, line: 22, offset: 335 },
          },
          selector: '.checkmark-icon',
        },
      ],
    ],
    [
      'is-checked',
      [
        {
          classes: ['is-checked'],
          code: normalizeFile([
            `.is-checked {`,
            `  background-color: #1976d2;`,
            `}`,
          ]),
          location: {
            end: { column: 1, line: 28, offset: 416 },
            start: { column: 1, line: 26, offset: 372 },
          },
          selector: '.is-checked',
        },
      ],
    ],
    [
      'is-disabled',
      [
        {
          classes: ['is-disabled'],
          code: normalizeFile([
            `.is-disabled {`,
            `  composes: input-disabled from global;`,
            `}`,
          ]),
          location: {
            end: { column: 1, line: 32, offset: 474 },
            start: { column: 1, line: 30, offset: 418 },
          },
          selector: '.is-disabled',
        },
        {
          classes: ['is-disabled', 'checkmark-icon'],
          code: normalizeFile([
            `.is-disabled .checkmark-icon {`,
            `  color: #546e7a;`,
            `}`,
          ]),
          location: {
            end: { column: 1, line: 36, offset: 526 },
            start: { column: 1, line: 34, offset: 476 },
          },
          selector: '.is-disabled .checkmark-icon',
        },
      ],
    ],
  ]);

  assert.strictEqual(
    addLocalClasses(file, {
      classToStyles,
      isHbs: false,
    }),
    normalizeFile([
      `<UiFormField`,
      `  @errorMessage={{this.errorMessage}}`,
      `  @isInline={{@isInline}}`,
      `  @isWide={{@isWide}}`,
      `>`,
      `  <:label as |l|>`,
      `    <label data-test-label id={{concat l.inputId "-label"}}>`,
      `      {{@label}}`,
      ``,
      `      {{#if @isRequired}}`,
      `        <span aria-hidden="true">`,
      `          *`,
      `        </span>`,
      `      {{/if}}`,
      `    </label>`,
      `  </:label>`,
      ``,
      `  <:field as |f|>`,
      `    <span`,
      `      aria-checked={{if this.isChecked "true" "false"}}`,
      `      aria-disabled={{if @isDisabled "true" "false"}}`,
      `      aria-labelledby={{concat f.inputId "-label"}}`,
      `      aria-readonly={{if @isReadOnly "true" "false"}}`,
      `      aria-required={{if @isRequired "true" "false"}}`,
      `      class="{{styles.checkbox}} {{if this.isChecked styles.is-checked}}  {{if (or @isDisabled @isReadOnly) styles.is-disabled}}  "`,
      `      data-test-field={{@label}}`,
      `      role="checkbox"`,
      `      tabindex={{unless @isDisabled "0"}}`,
      `      {{on "click" this.updateValue}}`,
      `      {{on "keypress" this.updateValueByPressingSpace}}`,
      `    >`,
      `      {{#if this.isChecked}}`,
      `        {{svgJar`,
      `          "check"`,
      `          class=styles.checkmark-icon`,
      `          desc="A checkmark to indicate that the input field is checked"`,
      `          role="img"`,
      `        }}`,
      `      {{/if}}`,
      `    </span>`,
      `  </:field>`,
      `</UiFormField>`,
    ]),
  );

  assert.strictEqual(
    addLocalClasses(file, {
      classToStyles,
      isHbs: true,
    }),
    normalizeFile([
      `<UiFormField`,
      `  @errorMessage={{this.errorMessage}}`,
      `  @isInline={{@isInline}}`,
      `  @isWide={{@isWide}}`,
      `>`,
      `  <:label as |l|>`,
      `    <label data-test-label id={{concat l.inputId "-label"}}>`,
      `      {{@label}}`,
      ``,
      `      {{#if @isRequired}}`,
      `        <span aria-hidden="true">`,
      `          *`,
      `        </span>`,
      `      {{/if}}`,
      `    </label>`,
      `  </:label>`,
      ``,
      `  <:field as |f|>`,
      `    <span`,
      `      aria-checked={{if this.isChecked "true" "false"}}`,
      `      aria-disabled={{if @isDisabled "true" "false"}}`,
      `      aria-labelledby={{concat f.inputId "-label"}}`,
      `      aria-readonly={{if @isReadOnly "true" "false"}}`,
      `      aria-required={{if @isRequired "true" "false"}}`,
      `      class="{{this.styles.checkbox}} {{if this.isChecked this.styles.is-checked}}  {{if (or @isDisabled @isReadOnly) this.styles.is-disabled}}  "`,
      `      data-test-field={{@label}}`,
      `      role="checkbox"`,
      `      tabindex={{unless @isDisabled "0"}}`,
      `      {{on "click" this.updateValue}}`,
      `      {{on "keypress" this.updateValueByPressingSpace}}`,
      `    >`,
      `      {{#if this.isChecked}}`,
      `        {{svgJar`,
      `          "check"`,
      `          class=this.styles.checkmark-icon`,
      `          desc="A checkmark to indicate that the input field is checked"`,
      `          role="img"`,
      `        }}`,
      `      {{/if}}`,
      `    </span>`,
      `  </:field>`,
      `</UiFormField>`,
    ]),
  );
});
