import { assert, normalizeFile, test } from '@codemod-utils/tests';

import { addLocalClasses } from '../../../../src/utils/css/index.js';
import {
  classNameToStyles,
  templateFile,
} from '../../../helpers/utils/css/simple-case-4.js';

test('utils | css | add-local-classes > simple case (4)', function () {
  let output = addLocalClasses(templateFile, {
    classNameToStyles,
    isHbs: false,
  });

  assert.strictEqual(
    output,
    normalizeFile([
      `<UiFormField`,
      `  @errorMessage={{this.errorMessage}}`,
      `  @isInline={{@isInline}}`,
      `  @isWide={{@isWide}}`,
      `>`,
      `  <:label as |l|>`,
      `    <label data-test-label id={{concat l.inputId "-label"}}>`,
      `      {{@label}}`,
      ``,
      `      {{#if @isRequired}}`,
      `        <span aria-hidden="true">`,
      `          *`,
      `        </span>`,
      `      {{/if}}`,
      `    </label>`,
      `  </:label>`,
      ``,
      `  <:field as |f|>`,
      `    <span`,
      `      aria-checked={{if this.isChecked "true" "false"}}`,
      `      aria-disabled={{if @isDisabled "true" "false"}}`,
      `      aria-labelledby={{concat f.inputId "-label"}}`,
      `      aria-readonly={{if @isReadOnly "true" "false"}}`,
      `      aria-required={{if @isRequired "true" "false"}}`,
      `      class="{{styles.checkbox}} {{if this.isChecked styles.is-checked}}  {{if (or @isDisabled @isReadOnly) styles.is-disabled}}  "`,
      `      data-test-field={{@label}}`,
      `      role="checkbox"`,
      `      tabindex={{unless @isDisabled "0"}}`,
      `      {{on "click" this.updateValue}}`,
      `      {{on "keypress" this.updateValueByPressingSpace}}`,
      `    >`,
      `      {{#if this.isChecked}}`,
      `        {{svgJar`,
      `          "check"`,
      `          class=styles.checkmark-icon`,
      `          desc="A checkmark to indicate that the input field is checked"`,
      `          role="img"`,
      `        }}`,
      `      {{/if}}`,
      `    </span>`,
      `  </:field>`,
      `</UiFormField>`,
    ]),
  );

  output = addLocalClasses(templateFile, {
    classNameToStyles,
    isHbs: true,
  });

  assert.strictEqual(
    output,
    normalizeFile([
      `<UiFormField`,
      `  @errorMessage={{this.errorMessage}}`,
      `  @isInline={{@isInline}}`,
      `  @isWide={{@isWide}}`,
      `>`,
      `  <:label as |l|>`,
      `    <label data-test-label id={{concat l.inputId "-label"}}>`,
      `      {{@label}}`,
      ``,
      `      {{#if @isRequired}}`,
      `        <span aria-hidden="true">`,
      `          *`,
      `        </span>`,
      `      {{/if}}`,
      `    </label>`,
      `  </:label>`,
      ``,
      `  <:field as |f|>`,
      `    <span`,
      `      aria-checked={{if this.isChecked "true" "false"}}`,
      `      aria-disabled={{if @isDisabled "true" "false"}}`,
      `      aria-labelledby={{concat f.inputId "-label"}}`,
      `      aria-readonly={{if @isReadOnly "true" "false"}}`,
      `      aria-required={{if @isRequired "true" "false"}}`,
      `      class="{{this.styles.checkbox}} {{if this.isChecked this.styles.is-checked}}  {{if (or @isDisabled @isReadOnly) this.styles.is-disabled}}  "`,
      `      data-test-field={{@label}}`,
      `      role="checkbox"`,
      `      tabindex={{unless @isDisabled "0"}}`,
      `      {{on "click" this.updateValue}}`,
      `      {{on "keypress" this.updateValueByPressingSpace}}`,
      `    >`,
      `      {{#if this.isChecked}}`,
      `        {{svgJar`,
      `          "check"`,
      `          class=this.styles.checkmark-icon`,
      `          desc="A checkmark to indicate that the input field is checked"`,
      `          role="img"`,
      `        }}`,
      `      {{/if}}`,
      `    </span>`,
      `  </:field>`,
      `</UiFormField>`,
    ]),
  );
});
