import { assert, normalizeFile, test } from '@codemod-utils/tests';

import { printStyles } from '../../../../src/utils/css/index.js';

test('utils | css | print-styles > complex case (3)', function () {
  const styles = [
    {
      classNames: ['container'],
      code: normalizeFile([
        `.container {`,
        `  column-gap: 2.5rem;`,
        `  display: grid;`,
        `  grid-template-areas:`,
        `    "summary summary"`,
        `    "previous-button next-button";`,
        `  grid-template-columns: 1fr 1fr;`,
        `  grid-template-rows: 1fr auto;`,
        `  height: 100%;`,
        `  overflow: hidden;`,
        `  row-gap: 1rem;`,
        `  width: 100%;`,
        `}`,
      ]),
      line: 1,
      selector: '.container',
    },
    {
      classNames: ['container', 'flat'],
      code: normalizeFile([
        `.container.flat {`,
        `  column-gap: 1rem;`,
        `  grid-template-areas: "previous-button summary next-button";`,
        `  grid-template-columns: 2.5rem 1fr 2.5rem;`,
        `  grid-template-rows: minmax(3rem, 1fr);`,
        `}`,
      ]),
      line: 85,
      selector: '.container.flat',
    },
    {
      classNames: ['container', 'flat', 'summary', 'horizontal-layout'],
      code: normalizeFile([
        `.container.flat .summary.horizontal-layout {`,
        `  gap: 0.5rem;`,
        `  grid-template-areas: "music-format annual-revenue relevant-years";`,
        `  grid-template-columns: 40% 1fr 1fr;`,
        `  grid-template-rows: 1fr;`,
        `}`,
      ]),
      line: 92,
      selector: '.container.flat .summary.horizontal-layout',
    },
    {
      classNames: ['container', 'flat', 'annual-revenue'],
      code: normalizeFile([
        `.container.flat .annual-revenue {`,
        `  display: flex;`,
        `  flex-direction: column;`,
        `}`,
      ]),
      line: 99,
      selector: '.container.flat .annual-revenue',
    },
    {
      classNames: ['container', 'flat', 'relevant-years'],
      code: normalizeFile([
        `.container.flat .relevant-years {`,
        `  display: flex;`,
        `  flex-direction: column;`,
        `}`,
      ]),
      line: 99,
      selector: '.container.flat .relevant-years',
    },
    {
      classNames: ['container', 'flat', 'previous-button'],
      code: normalizeFile([
        `.container.flat .previous-button {`,
        `  background: linear-gradient(36deg, #7cb342 16%, #4b830d 84%);`,
        `  border: 0;`,
        `}`,
      ]),
      line: 105,
      selector: '.container.flat .previous-button',
    },
    {
      classNames: ['container', 'flat', 'next-button'],
      code: normalizeFile([
        `.container.flat .next-button {`,
        `  background: linear-gradient(36deg, #7cb342 16%, #4b830d 84%);`,
        `  border: 0;`,
        `}`,
      ]),
      line: 105,
      selector: '.container.flat .next-button',
    },
  ];

  assert.strictEqual(
    printStyles(styles),
    normalizeFile([
      `.container {`,
      `  column-gap: 2.5rem;`,
      `  display: grid;`,
      `  grid-template-areas:`,
      `    "summary summary"`,
      `    "previous-button next-button";`,
      `  grid-template-columns: 1fr 1fr;`,
      `  grid-template-rows: 1fr auto;`,
      `  height: 100%;`,
      `  overflow: hidden;`,
      `  row-gap: 1rem;`,
      `  width: 100%;`,
      `}`,
      ``,
      `.container.flat {`,
      `  column-gap: 1rem;`,
      `  grid-template-areas: "previous-button summary next-button";`,
      `  grid-template-columns: 2.5rem 1fr 2.5rem;`,
      `  grid-template-rows: minmax(3rem, 1fr);`,
      `}`,
      ``,
      `.container.flat .summary.horizontal-layout {`,
      `  gap: 0.5rem;`,
      `  grid-template-areas: "music-format annual-revenue relevant-years";`,
      `  grid-template-columns: 40% 1fr 1fr;`,
      `  grid-template-rows: 1fr;`,
      `}`,
      ``,
      `.container.flat .annual-revenue {`,
      `  display: flex;`,
      `  flex-direction: column;`,
      `}`,
      ``,
      `.container.flat .relevant-years {`,
      `  display: flex;`,
      `  flex-direction: column;`,
      `}`,
      ``,
      `.container.flat .previous-button {`,
      `  background: linear-gradient(36deg, #7cb342 16%, #4b830d 84%);`,
      `  border: 0;`,
      `}`,
      ``,
      `.container.flat .next-button {`,
      `  background: linear-gradient(36deg, #7cb342 16%, #4b830d 84%);`,
      `  border: 0;`,
      `}`,
    ]),
  );
});
